# Working with Numpy

Numpy is the numerical python package, with a lot of mathematical capabilities. Before we can use it, we need to first import the package. We will import it under the name np such that we can afterwards refer to it by this short name.

In [8]:
import numpy as np

In the cell below, generate two 2x3 array with all elements equal to 1 - assign one of the arrays to the variable a and the other one to b. Add the two arrays. What do you get?

In [32]:
a = np.ones([2, 3])
b = np.ones([2, 3])
a + b

array([[2., 2., 2.],
       [2., 2., 2.]])

Now generate another array c which is a 3x2 array with all elements equal to 1. Are you able to add a and c? Why or why not?

In [33]:
c = np.ones([3, 2])
a + c

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Transpose c so that it has the same structure of a (i.e. become a 2x3 array). Assign the transposed array to variable "d". Are you able to add a and d?

In [34]:
d = c.transpose()
a + d

array([[2., 2., 2.],
       [2., 2., 2.]])

Which combination of arrays are you able to multiply with each other? Why?

In [39]:
a * b
a * d

array([[1., 1., 1.],
       [1., 1., 1.]])

Create a list which contains the numbers from 0 to 10. Square the list elementwise using numpy functions.

In [41]:
thislist = list(range(11))
list(np.square(np.array(thislist)))

array([[4., 4., 4.],
       [4., 4., 4.]])

Create a numpy array of size 10x10 which has random numbers between 0 and 100 on the main diagonal and zeros otherwise.

In [55]:
np.eye(10)*np.random.randint(100, size=10)

array([[58.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., 15.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., 15.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., 69.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  3.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., 81.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., 12.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 40.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  4.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 61.]])