# The Numpy Package

#### Importing and working with the package

In [51]:
import numpy

In [52]:
numpy?

In [53]:
import numpy as np


#### Numpy data structures: arrays

In [54]:
a = np.random.random((2, 3, 5))

In [55]:
print(a)

[[[0.29741417 0.97576913 0.00123844 0.84777876 0.93840907]
  [0.36052392 0.6830893  0.46484724 0.66064581 0.70490264]
  [0.67449165 0.26244965 0.76578421 0.47864934 0.02098919]]

 [[0.59625714 0.72641189 0.59696288 0.66342725 0.16394495]
  [0.13429663 0.30349888 0.89953311 0.55906956 0.40574699]
  [0.38594497 0.17823099 0.81859363 0.46100893 0.31519695]]]


In [56]:
print(a.shape)
print(a.size)

(2, 3, 5)
30


#### Extracting data from arrays

In [57]:
a[0,0,0]
a[0,:,2]

array([0.00123844, 0.46484724, 0.76578421])

In [58]:
# numpy arrays are mutable!
a[0,0,0] = 5
a

array([[[5.00000000e+00, 9.75769130e-01, 1.23843839e-03, 8.47778759e-01,
         9.38409075e-01],
        [3.60523922e-01, 6.83089296e-01, 4.64847238e-01, 6.60645807e-01,
         7.04902643e-01],
        [6.74491650e-01, 2.62449654e-01, 7.65784209e-01, 4.78649337e-01,
         2.09891896e-02]],

       [[5.96257143e-01, 7.26411894e-01, 5.96962879e-01, 6.63427254e-01,
         1.63944947e-01],
        [1.34296627e-01, 3.03498879e-01, 8.99533114e-01, 5.59069565e-01,
         4.05746987e-01],
        [3.85944965e-01, 1.78230990e-01, 8.18593625e-01, 4.61008933e-01,
         3.15196950e-01]]])

#### Converting other data structures to arrays

In [59]:
mylist1 = ['cat', 'dog']
mylist2 = [['cat', 'dog'], ['squirrel', 'mouse'], ['anteater', 'bear']]

In [60]:
np.array(mylist1)

array(['cat', 'dog'], dtype='<U3')

In [61]:
np.array(mylist2)

array([['cat', 'dog'],
       ['squirrel', 'mouse'],
       ['anteater', 'bear']], dtype='<U8')

In [62]:
test = [4, 5, 6, 7, 8, 2, 4, 5, 6]
np.array(test + mylist)

array([4, 5, 6, 7, 8, 2, 4, 5, 6, list(['cat', 'dog']),
       list(['squirrel', 'mouse']), list(['anteater', 'bear'])],
      dtype=object)

#### Element-wise mathematical operations

In [63]:
first = np.random.random((3, 4))
second = np.random.random((3, 4))
print(first)
print(second)

[[0.62510694 0.23937774 0.79160688 0.22818505]
 [0.69330025 0.27854171 0.25535333 0.90521148]
 [0.04716762 0.06241652 0.40958252 0.77294959]]
[[0.70486755 0.35464579 0.27203457 0.87450304]
 [0.5633216  0.86495626 0.89099352 0.3437802 ]
 [0.14438665 0.67568645 0.66879595 0.65103946]]


In [64]:
result = np.add(first, second)
print(result)

[[1.32997449 0.59402353 1.06364146 1.10268809]
 [1.25662185 1.14349797 1.14634685 1.24899168]
 [0.19155428 0.73810297 1.07837847 1.42398905]]


In [65]:
first + second

array([[1.32997449, 0.59402353, 1.06364146, 1.10268809],
       [1.25662185, 1.14349797, 1.14634685, 1.24899168],
       [0.19155428, 0.73810297, 1.07837847, 1.42398905]])

In [66]:
[1, 2, 4] + [1, 2, 3]

[1, 2, 4, 1, 2, 3]

In [67]:
np.add([1, 2, 4], [1, 2, 3])

array([2, 4, 7])